	<ul id="nav">
		<li><a href="/">home</a></li>
		<!-- li><a href="/news/index.html">news</a></li -->
		<li><a href="/about.html">about</a></li>
		<li><a href="/demos/">demos</a></li>
		<li><a href="/vrml/">vrml</a></li>
		<li><a href="/portfolio/">portfolio</a></li>
		<li><a href="/junkyard/">junkyard</a></li>
		<!-- li><a href="/3d/">3d</a></li -->
		<li><a href="/contact.html">contact</a></li>
	</ul>
