	<ul id="nav">
		<li><a href="/index.html">.home</a></li>
		<li><a href="/news/index.html">.news</a></li>
		<li><a href="/about.html">.about</a></li>
		<li><a href="/contact.html">.contact</a></li>
		<li><a href="/portfolio/index.html">.portfolio</a></li>
		<li><a href="/junkyard/index.html">.javascript junkyard</a></li>
		<li><a href="/dumpster/index.html">.dynamic dumpster</a></li>
		<li><a href="/dhtml/index.html">.dhtml dev</a></li>
		<li><a href="/vrml/index.html">.vrml</a></li>
		<li><a href="/3d/index.html">.3d</a></li>
	</ul>
